const reposData = [
  {
    id: 1,
    name: "ReactApp",
    description:
      "Eine React-Anwendung mit Beispielen zu Schleifen, Komponenten und State-Management.",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 12,
    forks: 3,
    lastUpdate: "2026-03-18",
    url: "https://github.com/derid149/ReactApp",
    openIssues: 2,
    license: "MIT",
    createdAt: "2025-11-10",
    visibility: "public",
  },
  {
    id: 2,
    name: "api-backend",
    description:
      "REST-API Backend mit Express.js und MongoDB für Benutzerverwaltung und Authentifizierung.",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 8,
    forks: 1,
    lastUpdate: "2026-03-15",
    url: "https://github.com/derid149/api-backend",
    openIssues: 5,
    license: "Apache-2.0",
    createdAt: "2025-09-22",
    visibility: "public",
  },
  {
    id: 3,
    name: "python-scripts",
    description:
      "Sammlung nützlicher Python-Skripte für Automatisierung, Datenverarbeitung und Web-Scraping.",
    language: "Python",
    languageColor: "#3572A5",
    stars: 24,
    forks: 7,
    lastUpdate: "2026-02-28",
    url: "https://github.com/derid149/python-scripts",
    openIssues: 0,
    license: "MIT",
    createdAt: "2025-06-15",
    visibility: "public",
  },
  {
    id: 4,
    name: "portfolio-website",
    description:
      "Persönliche Portfolio-Webseite mit HTML, CSS und JavaScript. Responsive Design mit Dark Mode.",
    language: "HTML",
    languageColor: "#e34c26",
    stars: 5,
    forks: 2,
    lastUpdate: "2026-01-20",
    url: "https://github.com/derid149/portfolio-website",
    openIssues: 1,
    license: "MIT",
    createdAt: "2025-08-03",
    visibility: "public",
  },
  {
    id: 5,
    name: "dotfiles",
    description:
      "Persönliche Konfigurationsdateien für Bash, Git, VSCode und andere Entwickler-Tools.",
    language: "Shell",
    languageColor: "#89e051",
    stars: 3,
    forks: 0,
    lastUpdate: "2026-03-10",
    url: "https://github.com/derid149/dotfiles",
    openIssues: 0,
    license: null,
    createdAt: "2025-04-18",
    visibility: "private",
  },
  {
    id: 6,
    name: "java-algorithms",
    description:
      "Implementierungen klassischer Algorithmen und Datenstrukturen in Java für Lernzwecke.",
    language: "Java",
    languageColor: "#b07219",
    stars: 15,
    forks: 4,
    lastUpdate: "2025-12-05",
    url: "https://github.com/derid149/java-algorithms",
    openIssues: 3,
    license: "GPL-3.0",
    createdAt: "2025-03-01",
    visibility: "public",
  },
];

export default reposData;
